name: Gayish
options:
  bundleIdPrefix: com.demohive
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: zh-Hans
  xcodeVersion: "15.0"

settings:
  SWIFT_VERSION: "5.9"
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"

targets:
  Gayish:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - GayishApp
    info:
      path: GayishApp/Info.plist
      properties:
        CFBundleDisplayName: Gayish
        UILaunchScreen:
          UIColorName: LaunchScreenBackground
        NSPhotoLibraryUsageDescription: "我们需要访问您的相册来选择聊天截图"
        NSCameraUsageDescription: "我们需要使用相机来拍摄聊天截图"
        NSPhotoLibraryAddUsageDescription: "保存分享海报到相册"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
    settings:
      INFOPLIST_FILE: GayishApp/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.demohive.gayish
      SWIFT_VERSION: "5.9"
      TARGETED_DEVICE_FAMILY: "1,2"
      SUPPORTS_MACCATALYST: false
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""  # 自动签名，无需填写
      CODE_SIGN_IDENTITY: "iPhone Developer"
      PROVISIONING_PROFILE_SPECIFIER: ""